### ISSUE TITLE
遇到双休加班计算结果有误

### ISSUE THREAD

**Issue by oscarwin** [zeakhold/x-box#1]
双休加班，加班满8小时，餐补是30，但是该插件还是按照15来计算的

**Comment by Quilljou** [comment]
希望支持修改某天的加班金额，场景是有的时候不算加班，你懂的

**Comment by danielzhang5566** [comment]
@oscarwin 周末的计算规则修正了，Chrome商店已更新。

**Comment by danielzhang5566** [comment]
@Quilljou 可以有，加个点击撤销高亮。

**Comment by danielzhang5566** [comment]
插件设置中支持指定“排除日期”，Chrome商店已更新。

**Comment by Quilljou** [comment]
那关掉 issue 吧
